Plan9port changes rebased onto golang/go master (as of April 4)
Harvey-OS/gone pull request #6
Opened 2018-04-10 05:25 UTC by msingle

after following directions better, successfully cross-compiled an executable that runs in harvey!

2018-04-10 05:25 UTC, bldybuild commented
Commits 5c3cb64b2e6285b672bb6ec9e42946ac974491dd, 1101a902fe7dba7285e88c94d73489cc2b7b2511, 168cc7ff9c09f2b19a354084ee5653c03d481e36, 4b06d9d72747b0407e2cd9a423b689c7e9c8e92d, 4b837c702340d23bdf28b98f44ab18a8da33fdcb, 26d74e8b65afeb856967cc264269cea9e1e7d2eb, 7974f0815e071448cd429d7c30c1d6c24b04a589, 910c3a9dfc4ff8ea4c25d725783bce4887d790f2, bfa8b6f8ffa49b3e5796af45a2f0bf9714a37bb9, e22d24131c8075c344fef790a93ec1addc2663e6, c12b185a6ed143e7b397bd58489866505756be0e, 7673e30503e3864265a842ec3e4200b317fc571d, 9c312245ac53f9d5a3f42eae10abb15f881da216, ae10914e67e6e99fec94b3d190558131a24ecd8e, f45c07e84ad17dcc4d927fb6571f81fc9fd99cdf, be371edd677abe6de310c9ffc225b9e8b052d2b8, 983dcf70ba065bcfe4772c6a1ddd44a1531629d7, 8a1519249fb482c9ae0831913d7a963e052cb97a, 2638001e12fe91736c6872cdd818fecc36d98c5e, 5f0a9ba1342674b3209c13035b5aa39a96dbd80c, 041c5d83486fce4a1c8b549a3c6f9c1951b0aea8, 77c3ef6f6fdb53708484e944f6ef37b222e1ae89, 2e84dc2596f5ca655fd5716e1c277a801c868566, 65727ab59d20663a76692fea7b8444dbb349080b, ff5cf43df5b1614f940157b21ca6ed64791b8a1f, 88129f0cb2438b555fd1dc74c707408251902b4e, 9eb219480e8de08d380ee052b7bff293856955f8, a3d8326993f25869ffb01f27a085abcfabbb42ef, 6633bb2aa7c8ab53dc6cc8a4ef8c4fef7a439cee and fc6280d4b01923dd377fa92a2b5dcaef5b253ef3 are not signed-off.

Please fix these issues:

>	1. Brad Fitzpatrick has not signed-off 5c3cb64.
>	2. jimmyfrasche has not signed-off 1101a90.
>	3. Alberto Donizetti has not signed-off 168cc7f.
>	4. Andrew Bonventre has not signed-off 4b06d9d.
>	5. jimmyfrasche has not signed-off 4b837c7.
>	6. Vlad Krasnov has not signed-off 26d74e8.
>	7. Andrew Bonventre has not signed-off 7974f08.
>	8. fanzha02 has not signed-off 910c3a9.
>	9. fanzha02 has not signed-off bfa8b6f.
>	10. Cherry Zhang has not signed-off e22d241.
>	11. Vladimir Kuzmin has not signed-off c12b185.
>	12. Fangming.Fang has not signed-off 7673e30.
>	13. Fangming.Fang has not signed-off 9c31224.
>	14. Michael Munday has not signed-off ae10914.
>	15. Than McIntosh has not signed-off f45c07e.
>	16. Alberto Donizetti has not signed-off be371ed.
>	17. Ilya Tocar has not signed-off 983dcf7.
>	18. Adam Langley has not signed-off 8a15192.
>	19. Paul Querna has not signed-off 2638001.
>	20. Hiroshi Ioka has not signed-off 5f0a9ba.
>	21. Alberto Donizetti has not signed-off 041c5d8.
>	22. Daniel Martí has not signed-off 77c3ef6.
>	23. Tobias Klauser has not signed-off 2e84dc2.
>	24. Ross Light has not signed-off 65727ab.
>	25. isharipo has not signed-off ff5cf43.
>	26. Tim Wright has not signed-off 88129f0.
>	27. Ilya Tocar has not signed-off 9eb2194.
>	28. Giovanni Bajo has not signed-off a3d8326.
>	29. Carlos Eduardo Seo has not signed-off 6633bb2.
>	30. Alberto Donizetti has not signed-off fc6280d.


If you'd like more information on how to sign your commits please visit [signed-off-by.me](https://signed-off-by.me)

2018-04-10 07:04 UTC, rminnich requested changes
Note that this is trying to merge into master, and we want it to merge into the plan9port branch.

2018-04-10 12:48 UTC, msingle commented
updated pr to be against plan9port

2018-04-17 22:27 UTC, rminnich approved these changes

2018-05-10 05:45 UTC, closed without merging